"""replace analyses.analysis_text with reflection JSONB list; add suggestions.explanation

Revision ID: 004
Revises: 003
Create Date: 2026-08-03

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Reflection moves from a single paragraph string to a list of
    # self-contained, situation-grounded strings -- dev-only DB, existing
    # analysis_text values are dropped rather than migrated (single trusted
    # local user, trivially regenerated by re-running an analysis).
    op.drop_column("analyses", "analysis_text")
    op.add_column(
        "analyses",
        sa.Column("reflection", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    )
    op.add_column(
        "suggestions",
        sa.Column("explanation", sa.Text(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    op.drop_column("suggestions", "explanation")
    op.drop_column("analyses", "reflection")
    op.add_column("analyses", sa.Column("analysis_text", sa.Text(), nullable=False, server_default=""))
